"""CISO strategic planning module decomposing extracted objectives into department task graphs (DAGs)."""

from typing import Any

import jinja2
from pydantic import BaseModel, Field

from app.ciso.intake_interpreter import InterpretedObjective
from app.ciso.prompts import CISO_PLANNING_PROMPT, CISO_SYSTEM_PROMPT
from app.core.logging import get_logger
from app.domain.engagement import RulesOfEngagementSchema
from app.domain.seed import SEED_DEPARTMENTS, SEED_ROLES
from app.llm.interface import AgentBrain

logger = get_logger("ciso.planner")


class PlannedTask(BaseModel):
    """Discrete task in the strategic decomposition plan."""

    task_id: str = Field(description="Unique task identifier (e.g. TASK_01_RECON)")
    title: str = Field(description="Clear title of the task")
    department_id: str = Field(description="Registered department ID (e.g. dept_recon)")
    assigned_role: str = Field(
        description="Registered specialist role ID (e.g. role_web_discovery)"
    )
    priority: int = Field(default=2, ge=1, le=4)
    depends_on_task_ids: list[str] = Field(
        default_factory=list, description="List of prerequisite task IDs"
    )
    requires_approval_gate: str | None = Field(
        default=None, description="Gated approval category if required"
    )
    input_context: dict[str, Any] = Field(
        default_factory=dict, description="Task execution parameters"
    )
    estimated_duration_sec: int = Field(default=120)
    success_criteria: str = Field(
        default="", description="Expected deliverable or finding artifact"
    )


class CisoStrategicPlan(BaseModel):
    """Structured decomposition plan generated by the CISO Agent."""

    engagement_id: str
    mission_title: str
    departments_involved: list[str] = Field(default_factory=list)
    tasks: list[PlannedTask] = Field(description="Ordered list of discrete tasks forming a DAG")
    total_tasks: int = Field(default=0)
    risk_assessment_summary: str = Field(default="")
    registry_validation_passed: bool = Field(default=True)
    validation_errors: list[str] = Field(default_factory=list)


class CisoStrategicPlanner:
    """CISO strategic reasoning engine generating validated, non-hallucinated department/task DAG plans."""

    def __init__(self, brain: AgentBrain) -> None:
        self.brain = brain
        self.template = jinja2.Template(CISO_PLANNING_PROMPT)

    @classmethod
    def get_canonical_hierarchy_map(cls) -> dict[str, list[str]]:
        """Return the mapping of registered department IDs to their valid specialist role IDs."""
        hierarchy: dict[str, list[str]] = {d.id: [] for d in SEED_DEPARTMENTS}
        for r in SEED_ROLES:
            if r.department_id in hierarchy:
                hierarchy[r.department_id].append(r.id)
        return hierarchy

    async def generate_strategic_plan(
        self,
        engagement_id: str,
        mission_title: str,
        objectives: list[InterpretedObjective],
        rules_of_engagement: RulesOfEngagementSchema,
        hierarchy_map: dict[str, list[str]] | None = None,
        max_retries: int = 2,
    ) -> CisoStrategicPlan:
        """Generate a structured CisoStrategicPlan with strict role/department registry validation."""
        available_hierarchy = hierarchy_map or self.get_canonical_hierarchy_map()

        rendered_prompt = self.template.render(
            engagement_id=engagement_id,
            mission_title=mission_title,
            objectives=[obj.model_dump() for obj in objectives],
            rules_of_engagement=rules_of_engagement.model_dump(),
            available_hierarchy=available_hierarchy,
        )

        last_error_detail: str | None = None

        for attempt in range(max_retries + 1):
            try:
                current_prompt = rendered_prompt
                if attempt > 0 and last_error_detail:
                    current_prompt += (
                        f"\n\n[SELF-CORRECTION NOTICE - ATTEMPT {attempt + 1}]\n"
                        f"Your previous plan had registry validation errors: {last_error_detail}\n"
                        f"Ensure every task strictly uses registered department_ids and assigned_roles from the provided hierarchy."
                    )

                logger.info(
                    "Generating strategic plan via CISO AgentBrain",
                    engagement_id=engagement_id,
                    attempt=attempt + 1,
                )

                response = await self.brain.generate(
                    prompt=current_prompt,
                    system_prompt=CISO_SYSTEM_PROMPT,
                    response_schema=CisoStrategicPlan,
                    temperature=0.2,
                )

                if response.structured_data and isinstance(
                    response.structured_data, CisoStrategicPlan
                ):
                    plan: CisoStrategicPlan = response.structured_data
                else:
                    plan = CisoStrategicPlan.model_validate_json(response.content)

                # Validate against known role/department registry
                validated_plan = self.validate_plan_against_registry(plan, available_hierarchy)
                if validated_plan.registry_validation_passed:
                    return validated_plan

                # If validation failed on hallucinated roles, trigger retry
                last_error_detail = "; ".join(validated_plan.validation_errors)
                logger.warning(
                    f"Plan failed registry validation on attempt {attempt + 1}: {last_error_detail}"
                )

            except Exception as err:
                last_error_detail = str(err)
                logger.warning(
                    f"Plan generation failed on attempt {attempt + 1}: {err}",
                    engagement_id=engagement_id,
                )

        # Fallback plan if all retries fail
        logger.error(
            "CISO planner exhausted retries. Returning safe baseline fallback plan.",
            engagement_id=engagement_id,
        )
        return self._create_fallback_plan(
            engagement_id=engagement_id,
            mission_title=mission_title,
            objectives=objectives,
            error_reason=last_error_detail or "Validation failed",
        )

    def validate_plan_against_registry(
        self,
        plan: CisoStrategicPlan,
        hierarchy_map: dict[str, list[str]],
    ) -> CisoStrategicPlan:
        """Validate that all tasks in the plan reference registered departments and roles with valid DAG edges."""
        validation_errors: list[str] = []
        valid_departments = set(hierarchy_map.keys())
        all_valid_roles = {role for roles in hierarchy_map.values() for role in roles}

        known_task_ids = {t.task_id for t in plan.tasks}
        sanitized_tasks: list[PlannedTask] = []
        departments_used = set()

        for task in plan.tasks:
            # 1. Department validity check
            if task.department_id not in valid_departments:
                validation_errors.append(
                    f"Task '{task.task_id}' references unknown department '{task.department_id}'."
                )

            # 2. Role validity check (Anti-hallucination guardrail)
            if task.assigned_role not in all_valid_roles:
                validation_errors.append(
                    f"Task '{task.task_id}' references unknown role '{task.assigned_role}'."
                )
            else:
                # Check role belongs to department
                dept_roles = hierarchy_map.get(task.department_id, [])
                if task.assigned_role not in dept_roles:
                    validation_errors.append(
                        f"Task '{task.task_id}' role '{task.assigned_role}' does not belong to department '{task.department_id}'."
                    )

            # 3. Dependency graph integrity checks
            for dep_id in task.depends_on_task_ids:
                if dep_id == task.task_id:
                    validation_errors.append(
                        f"Task '{task.task_id}' has an illegal self-dependency on itself."
                    )
                elif dep_id not in known_task_ids:
                    validation_errors.append(
                        f"Task '{task.task_id}' references non-existent prerequisite task '{dep_id}'."
                    )

            departments_used.add(task.department_id)
            sanitized_tasks.append(task)

        is_passed = len(validation_errors) == 0

        return CisoStrategicPlan(
            engagement_id=plan.engagement_id,
            mission_title=plan.mission_title,
            departments_involved=list(departments_used),
            tasks=sanitized_tasks,
            total_tasks=len(sanitized_tasks),
            risk_assessment_summary=plan.risk_assessment_summary,
            registry_validation_passed=is_passed,
            validation_errors=validation_errors,
        )

    def _create_fallback_plan(
        self,
        engagement_id: str,
        mission_title: str,
        objectives: list[InterpretedObjective],
        error_reason: str,
    ) -> CisoStrategicPlan:
        """Create a safe 3-task sequential baseline plan conforming to the MVP specification."""
        tasks = [
            PlannedTask(
                task_id="TASK_01_RECON",
                title="Perimeter Reconnaissance & Service Discovery",
                department_id="dept_recon",
                assigned_role="role_web_discovery",
                priority=3,
                depends_on_task_ids=[],
                estimated_duration_sec=60,
                success_criteria="Attack surface endpoints identified",
            ),
            PlannedTask(
                task_id="TASK_02_VULN_SCAN",
                title="Vulnerability Assessment & Exposure Validation",
                department_id="dept_vulnerability",
                assigned_role="role_web_vuln_assessor",
                priority=3,
                depends_on_task_ids=["TASK_01_RECON"],
                requires_approval_gate="ACTIVE_EXPLOITATION_PROBE",
                estimated_duration_sec=120,
                success_criteria="Vulnerability findings verified",
            ),
            PlannedTask(
                task_id="TASK_03_REPORT",
                title="Penetration Testing Deliverable Compilation",
                department_id="dept_reporting",
                assigned_role="role_technical_writer",
                priority=2,
                depends_on_task_ids=["TASK_02_VULN_SCAN"],
                estimated_duration_sec=60,
                success_criteria="Final Markdown/PDF report compiled",
            ),
        ]

        return CisoStrategicPlan(
            engagement_id=engagement_id,
            mission_title=mission_title,
            departments_involved=["dept_recon", "dept_vulnerability", "dept_reporting"],
            tasks=tasks,
            total_tasks=len(tasks),
            risk_assessment_summary="Fallback Baseline Plan generated due to LLM planner validation fault.",
            registry_validation_passed=True,
            validation_errors=[f"Fallback triggered: {error_reason}"],
        )
